name: "Quality"

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Run quality checks on ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2']

    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2

      - name: PHP Version
        run: php -v

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Install Dependencies
        run: composer install

      - name: Run parallel-lint
        run: vendor/bin/parallel-lint --exclude .git --exclude vendor .

      - name: Check coding style
        run: vendor/bin/phpcs

      - name: Static code analysis
        run: vendor/bin/psalm --show-info=true

      - name: Run tests
        run: vendor/bin/phpunit --testdox
