name: "Quality"

on: [push, pull_request]

jobs:
  build:
    name: Run quality checks on ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        php: ['8.0', '8.1', '8.2']

  steps:
    - uses: actions/checkout@main

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer:v2

    - name: PHP Version
      run: php -v

    - name: Install dependencies
      run: composer install -o --prefer-dist --no-progress --no-suggest

    - name: Check coding style
      run: vendor/bin/phpcs

    - name: Static code analysis
      run: vendor/bin/psalm --show-info=true

    - name: Run tests
      run: vendor/bin/phpunit --testdox
